"""ReAct loop — the core of the agent.

Implements the cycle: thought → tool call → observation → repeat
until the agent calls generate_report or reaches the max iterations.
Works with both Claude and Gemini via the abstraction layer in llm/client.py.
"""

from pydantic import ValidationError

from gitdiligence.agent.prompts import build_system_prompt
from gitdiligence.agent.state import AgentState, Step
from gitdiligence.llm.client import call_llm, format_assistant_message, format_tool_results
from gitdiligence.report.schema import DiligenceReport
from gitdiligence.tools import registry

MAX_ITERATIONS = 25


def _build_generate_report_tool() -> dict:
    """Build the generate_report tool definition.

    Uses the JSON Schema generated by Pydantic so the LLM knows
    exactly what format to produce.
    """
    return {
        "name": "generate_report",
        "description": "Produce the final due diligence report. Call this tool when you have enough information.",
        "input_schema": DiligenceReport.model_json_schema(),
    }


def run_agent(
    owner: str,
    repo: str,
    model: str = "gemini-2.5-flash",
    max_steps: int = MAX_ITERATIONS,
    verbose: bool = False,
) -> AgentState:
    """Run the ReAct agent on a GitHub repo.

    Returns the AgentState with the report and steps.
    """
    state = AgentState(owner=owner, repo=repo)
    system = build_system_prompt(owner, repo)

    # First message: request analysis
    state.messages.append({
        "role": "user",
        "content": f"Analyze the repo {owner}/{repo}",
    })

    # Available tools
    tools = registry.all_tools()
    generate_report_tool = _build_generate_report_tool()

    for iteration in range(max_steps):
        if verbose:
            print(f"\n--- Iteration {iteration + 1}/{max_steps} ---")

        # Call the LLM (Claude or Gemini depending on the model)
        response = call_llm(
            messages=state.messages,
            tools=tools,
            system=system,
            model=model,
            extra_tools=[generate_report_tool],
        )

        # Track token usage
        state.add_tokens(
            input_tokens=response.usage.input_tokens,
            output_tokens=response.usage.output_tokens,
        )

        # Reasoning
        if verbose and response.text:
            print(f"Thought: {response.text[:200]}...")

        # Add the LLM response to messages
        state.messages.append(format_assistant_message(response))

        # No tool call -> the LLM finished without a report
        if not response.tool_calls:
            if verbose:
                print("LLM finished without calling generate_report.")
            break

        # Execute each tool and collect results
        results = []
        done = False

        for tc in response.tool_calls:
            if verbose:
                print(f"Tool: {tc.name}({tc.input})")

            # Special case: generate_report -> validate and finish
            if tc.name == "generate_report":
                try:
                    state.report = DiligenceReport(**tc.input)
                    results.append({
                        "name": tc.name,
                        "id": tc.id,
                        "content": "Report validated successfully.",
                    })
                    state.add_step(Step(
                        tool_name=tc.name,
                        tool_input=tc.input,
                        result="Report validated.",
                        thought=response.text,
                    ))
                    if verbose:
                        print(f"Report generated! Verdict: {state.report.verdict}")
                    done = True

                except ValidationError as e:
                    error_msg = f"Invalid report: {e}"
                    results.append({
                        "name": tc.name,
                        "id": tc.id,
                        "content": error_msg,
                        "is_error": True,
                    })
                    if verbose:
                        print(f"Validation error: {e}")
                continue

            # Normal tool -> execute
            try:
                tool = registry.get_tool(tc.name)
                result = tool.execute(**tc.input)
            except Exception as e:
                result = f"Error executing {tc.name}: {e}"

            state.add_step(Step(
                tool_name=tc.name,
                tool_input=tc.input,
                result=result,
                thought=response.text,
            ))

            results.append({
                "name": tc.name,
                "id": tc.id,
                "content": result,
            })

            if verbose:
                print(f"Result: {result[:200]}...")

        # Send all results back to the LLM in a single message
        state.messages.append(format_tool_results(results, response.provider))

        if done:
            break

    return state
